In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 1. 데이터 로드하기

In [21]:
train = pd.read_csv('train.csv')
train.head()

,index,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,...,engnat,age,hand,religion,orientation,voted,married,familysize,ASD,nerdiness
0,0,1.0,5.0,5.0,5.0,1.0,4.0,5.0,5.0,1.0,...,1.0,20,2.0,12.0,4.0,2.0,1.0,4.0,2.0,1
1,1,4.0,4.0,4.0,4.0,4.0,5.0,4.0,4.0,3.0,...,1.0,49,1.0,2.0,1.0,1.0,2.0,4.0,2.0,1
2,2,4.0,5.0,5.0,4.0,3.0,5.0,5.0,5.0,4.0,...,2.0,43,1.0,2.0,2.0,2.0,3.0,4.0,2.0,1
3,3,4.0,4.0,4.0,2.0,4.0,3.0,3.0,5.0,3.0,...,1.0,17,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1
4,4,4.0,4.0,4.0,4.0,3.0,3.0,4.0,2.0,3.0,...,2.0,18,2.0,12.0,1.0,2.0,1.0,1.0,2.0,0

In [23]:
train.shape

(15000, 70)

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 70 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         15000 non-null  int64
 1   Q1            14959 non-null  float64
 2   Q2            14931 non-null  float64
 3   Q3            14950 non-null  float64
 4   Q4            14929 non-null  float64
 5   Q5            14962 non-null  float64
 6   Q6            14952 non-null  float64
 7   Q7            14924 non-null  float64
 8   Q8            14952 non-null  float64
 9   Q9            14944 non-null  float64
 10  Q10           14928 non-null  float64
 11  Q11           14941 non-null  float64
 12  Q12           14933 non-null  float64
 13  Q13           14960 non-null  float64
 14  Q14           14964 non-null  float64
 15  Q15           14955 non-null  float64
 16  Q16           14967 non-null  float64
 17  Q17           14963 non-null  float64
 18  Q18           14937 non-null  float64
 19  Q19           14947 non-null  float64
 20  Q20           14955 non-null  float64
 21  Q21           14961 non-null  float64
 22  Q22           14962 non-null  float64
 23  Q23           14950 non-null  float64
 24  Q24           14939 non-null  float64
 25  Q25           14956 non-null  float64
 26  Q26           14932 non-null  float64
 27  country       14810 non-null  object
 28  introelapse   15000 non-null  int64
 29  testelapse    15000 non-null  int64
 30  surveyelapse  15000 non-null  int64
 31  TIPI1         14947 non-null  float64
 32  TIPI2         14934 non-null  float64
 33  TIPI3         14921 non-null  float64
 34  TIPI4         14936 non-null  float64
 35  TIPI5         14930 non-null  float64
 36  TIPI6         14938 non-null  float64
 37  TIPI7         14936 non-null  float64
 38  TIPI8         14935 non-null  float64
 39  TIPI9         14936 non-null  float64
 40  TIPI10        14920 non-null  float64
 41  VCL1          15000 non-null  int64
 42  VCL2          15000 non-null  int64
 43  VCL3          15000 non-null  int64
 44  VCL4          15000 non-null  int64
 45  VCL5          15000 non-null  int64
 46  VCL6          15000 non-null  int64
 47  VCL7          15000 non-null  int64
 48  VCL8          15000 non-null  int64
 49  VCL9          15000 non-null  int64
 50  VCL10         15000 non-null  int64
 51  VCL11         15000 non-null  int64
 52  VCL12         15000 non-null  int64
 53  VCL13         15000 non-null  int64
 54  VCL14         15000 non-null  int64
 55  VCL15         15000 non-null  int64
 56  VCL16         15000 non-null  int64
 57  education     14833 non-null  float64
 58  urban         15000 non-null  int64
 59  gender        14981 non-null  float64
 60  engnat        14953 non-null  float64
 61  age           15000 non-null  int64
 62  hand          14953 non-null  float64
 63  religion      14755 non-null  float64
 64  orientation   14601 non-null  float64
 65  voted         14915 non-null  float64
 66  married       14918 non-null  float64
 67  familysize    14681 non-null  float64
 68  ASD           14911 non-null  float64
 69  nerdiness     15000 non-null  int64
dtypes: float64(46), int64(23), object(1)
memory usage: 8.0+ MB

In [10]:
train.isnull().sum()

index           0
Q1             41
Q2             69
Q3             50
Q4             71
             ...
voted          85
married        82
familysize    319
ASD            89
nerdiness       0
Length: 70, dtype: int64

In [20]:
train.corr()

,index,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,...,engnat,age,hand,religion,orientation,voted,married,familysize,ASD,nerdiness
index,1.000000,0.002305,-0.006634,-0.006673,-0.002626,0.005943,0.000750,-0.002735,0.000005,0.005412,...,-0.001678,0.003430,-0.003603,0.012452,0.005645,-0.002001,0.013029,-0.012597,-0.011918,0.002742
Q1,0.002305,1.000000,0.178780,0.384572,0.577053,0.223724,0.165841,0.107236,0.325043,0.170373,...,0.002724,0.001034,0.025820,-0.004076,0.152218,0.081037,-0.139189,0.005160,-0.119808,0.287806
Q2,-0.006634,0.178780,1.000000,0.144726,0.189041,0.169320,0.149096,0.343890,0.243801,0.195185,...,0.004070,-0.009369,0.042152,-0.030778,0.067099,-0.018493,-0.026384,0.005746,-0.037028,0.264779
Q3,-0.006673,0.384572,0.144726,1.000000,0.331697,0.146386,0.186024,0.079298,0.347291,0.088511,...,-0.012624,-0.031418,0.010728,-0.036708,0.154436,0.063986,-0.125866,0.005082,-0.094494,0.207495
Q4,-0.002626,0.577053,0.189041,0.331697,1.000000,0.267255,0.213572,0.131097,0.265842,0.209707,...,-0.074912,0.004220,0.046110,-0.023891,0.179834,0.027582,-0.077754,0.006740,-0.170143,0.267877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
voted,-0.002001,0.081037,-0.018493,0.063986,0.027582,-0.048147,-0.048738,-0.037632,0.084087,-0.028661,...,0.058976,-0.005759,0.005339,0.014004,0.057296,1.000000,-0.195881,-0.011203,-0.010133,-0.013185
married,0.013029,-0.139189,-0.026384,-0.125866,-0.077754,0.059669,0.049895,0.068314,-0.122479,0.051573,...,-0.121525,0.019450,0.000607,0.045140,-0.154953,-0.195881,1.000000,0.002020,0.041598,-0.025577
familysize,-0.012597,0.005160,0.005746,0.005082,0.006740,0.006881,0.008958,0.005682,0.005561,0.007621,...,0.005789,0.002232,0.030873,0.018815,0.020040,-0.011203,0.002020,1.000000,-0.031369,-0.011145
ASD,-0.011918,-0.119808,-0.037028,-0.094494,-0.170143,-0.079265,-0.039449,-0.024146,-0.053190,-0.035478,...,0.043208,0.003809,-0.040563,-0.012767,-0.092892,-0.010133,0.041598,-0.031369,1.000000,-0.056631
nerdiness,0.002742,0.287806,0.264779,0.207495,0.267877,0.236608,0.311261,0.206354,0.230176,0.226568,...,-0.055904,0.005443,0.013037,-0.036793,0.068105,-0.013185,-0.025577,-0.011145,-0.056631,1.000000

### 2. 데이터 전처리

In [14]:
X = train.drop(['nerdiness'], axis=1)
y = train['nerdiness']

In [25]:
train.corr().sort_values(by='nerdiness', ascending=False)

,index,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,...,engnat,age,hand,religion,orientation,voted,married,familysize,ASD,nerdiness
nerdiness,0.002742,0.287806,0.264779,0.207495,0.267877,0.236608,0.311261,0.206354,0.230176,0.226568,...,-0.055904,0.005443,0.013037,-0.036793,0.068105,-0.013185,-0.025577,-0.011145,-0.056631,1.000000
Q6,0.000750,0.165841,0.149096,0.186024,0.213572,0.306011,1.000000,0.186163,0.218073,0.387457,...,-0.115475,-0.002760,0.022344,-0.021954,0.055782,-0.048738,0.049895,0.008958,-0.039449,0.311261
Q1,0.002305,1.000000,0.178780,0.384572,0.577053,0.223724,0.165841,0.107236,0.325043,0.170373,...,0.002724,0.001034,0.025820,-0.004076,0.152218,0.081037,-0.139189,0.005160,-0.119808,0.287806
Q4,-0.002626,0.577053,0.189041,0.331697,1.000000,0.267255,0.213572,0.131097,0.265842,0.209707,...,-0.074912,0.004220,0.046110,-0.023891,0.179834,0.027582,-0.077754,0.006740,-0.170143,0.267877
Q2,-0.006634,0.178780,1.000000,0.144726,0.189041,0.169320,0.149096,0.343890,0.243801,0.195185,...,0.004070,-0.009369,0.042152,-0.030778,0.067099,-0.018493,-0.026384,0.005746,-0.037028,0.264779
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
religion,0.012452,-0.004076,-0.030778,-0.036708,-0.023891,-0.042419,-0.021954,-0.054148,-0.005044,-0.006449,...,-0.015146,-0.004324,0.001902,1.000000,-0.013550,0.014004,0.045140,0.018815,-0.012767,-0.036793
engnat,-0.001678,0.002724,0.004070,-0.012624,-0.074912,0.025236,-0.115475,0.018381,0.008082,0.002934,...,1.000000,-0.008892,-0.015720,-0.015146,-0.026135,0.058976,-0.121525,0.005789,0.043208,-0.055904
ASD,-0.011918,-0.119808,-0.037028,-0.094494,-0.170143,-0.079265,-0.039449,-0.024146,-0.053190,-0.035478,...,0.043208,0.003809,-0.040563,-0.012767,-0.092892,-0.010133,0.041598,-0.031369,1.000000,-0.056631
TIPI10,-0.004955,-0.130809,-0.087399,0.035084,-0.127894,-0.121732,-0.034153,-0.051375,-0.040259,-0.139973,...,0.003171,-0.010841,-0.038444,-0.020275,-0.059149,0.024528,-0.041712,-0.008774,0.032987,-0.095491
TIPI1,-0.020230,-0.170889,-0.038658,-0.410227,-0.153313,-0.100719,-0.134901,-0.017537,-0.244753,-0.035109,...,-0.008145,-0.010291,0.000317,0.072599,-0.116873,-0.042912,0.043023,-0.010271,0.061903,-0.103434

필요없는 column 삭제하기